puku_version = "1.0.0"
remote_file(
    name = "puku",
    url = f"https://github.com/please-build/puku/releases/download/v{puku_version}/puku-{puku_version}-{CONFIG.OS}_{CONFIG.ARCH}",
    binary = True,
)
