puku_version = "1.1.0"

remote_file(
    name = "puku",
    binary = True,
    url = f"https://github.com/please-build/puku/releases/download/v{puku_version}/puku-{puku_version}-{CONFIG.OS}_{CONFIG.ARCH}",
)
